#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create our folders
mkdir -p \
    /config/settings \
    /downloads

# default config file
cp -n \
    /defaults/pyload.cfg \
    /config/settings/pyload.cfg

# permissions
echo "[cont-init.d] Setting permissions this may take some time"
lsiown -R abc:abc \
    /config
lsiown abc:abc \
    /downloads
